export const registerFields: any[] = [
  {
    label: 'First name',
    name: 'first_name',
    type: 'text',
    placeholder: 'Enter First Name',
    autoComplete: 'off',
    required: true,
  },
  {
    label: 'Last name',
    name: 'last_name',
    type: 'text',
    placeholder: 'Enter Last Name',
    autoComplete: 'off',
  },
  {
    label: 'Phone Number',
    name: 'number',
    type: 'text',
    placeholder: 'Enter Phone Number',
    autoComplete: 'off',
    required: true,
  },
  {
    label: 'Email',
    name: 'email',
    type: 'text',
    placeholder: 'Enter Email',
    autoComplete: 'off',
    required: true,
  },
  {
    label: 'Password',
    name: 'password',
    type: 'password',
    placeholder: 'Enter Password',
    autoComplete: 'off',
    required: true,
  },
  {
    label: 'Confirm Password',
    name: 'repeat_password',
    type: 'password',
    placeholder: 'Enter Password',
    autoComplete: 'off',
    required: true,
  },
];
